//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace car2city
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.Vehiculoes = new HashSet<Vehiculo>();
            this.ViajeUsuarios = new HashSet<ViajeUsuario>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string usuario1 { get; set; }
        public string email { get; set; }
        public string sexo { get; set; }
        public Nullable<int> idPais { get; set; }
        public Nullable<int> idTipoDoc { get; set; }
        public Nullable<decimal> numeroDoc { get; set; }
        public string telefono { get; set; }
        public string imagen { get; set; }
        public Nullable<decimal> puntosConductor { get; set; }
        public Nullable<decimal> puntosPasajero { get; set; }
        public Nullable<decimal> kmAcumulados { get; set; }
        public Nullable<decimal> co2 { get; set; }
        public Nullable<System.DateTime> fechaRegistro { get; set; }
        public Nullable<System.DateTime> fechaIngreso { get; set; }
    
        public virtual Pai Pai { get; set; }
        public virtual TipoDocumento TipoDocumento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vehiculo> Vehiculoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ViajeUsuario> ViajeUsuarios { get; set; }
    }
}
