//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace car2city
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViajeCaracteristica
    {
        public int id { get; set; }
        public Nullable<int> idViaje { get; set; }
        public Nullable<int> asientos { get; set; }
        public Nullable<int> idEquipaje { get; set; }
        public Nullable<bool> bebida { get; set; }
        public Nullable<bool> comer { get; set; }
        public Nullable<bool> musica { get; set; }
        public Nullable<bool> fumar { get; set; }
        public Nullable<bool> mixto { get; set; }
        public Nullable<bool> mascota { get; set; }
        public Nullable<int> flexibilidad { get; set; }
        public Nullable<bool> aceptacion { get; set; }
    
        public virtual TipoEquipaje TipoEquipaje { get; set; }
        public virtual Viaje Viaje { get; set; }
    }
}
