//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace car2city
{
    using System;
    using System.Collections.Generic;
    
    public partial class Viaje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Viaje()
        {
            this.ViajeCaracteristicas = new HashSet<ViajeCaracteristica>();
            this.ViajeUsuarios = new HashSet<ViajeUsuario>();
        }
    
        public int id { get; set; }
        public string origen { get; set; }
        public string destino { get; set; }
        public Nullable<decimal> lat1 { get; set; }
        public Nullable<decimal> lng1 { get; set; }
        public Nullable<decimal> lat2 { get; set; }
        public Nullable<decimal> lng2 { get; set; }
        public Nullable<decimal> kilometros { get; set; }
        public Nullable<decimal> co2 { get; set; }
        public Nullable<int> idVehiculo { get; set; }
    
        public virtual Vehiculo Vehiculo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ViajeCaracteristica> ViajeCaracteristicas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ViajeUsuario> ViajeUsuarios { get; set; }
    }
}
