//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace car2city
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViajeUsuario
    {
        public int id { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public Nullable<int> idViaje { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Viaje Viaje { get; set; }
    }
}
